services:
  postgres:
    image: postgres:16
    container_name: fuel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fuel_admin
      POSTGRES_PASSWORD: fuel_admin_pw
      POSTGRES_DB: fuel_prices
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
